Clean up Docker instructions
rollkit/local-celestia-devnet pull request #57
Opened 2023-07-21 20:59 UTC by HCastano

Hey! I ended up running into an couple of issues when using the provided Docker command
since it was using a) an old version of the Celestia node and b) not forwarding the port
used by the JSON-RPC API.

I've updated the README accordingly.

---

On a sidenote, what's the difference between port 26657 and 26658. In the docs it says
both are for RPC but I don't see 26657 used anywhere.

Thanks!

2023-07-31 13:11 UTC, MSevey commented on README.md
> +Docker build . -t celestia-local-devnet
this should be reverted.

2023-07-31 13:12 UTC, MSevey commented
@HCastano thanks for the contribution!

2023-07-31 13:15 UTC, jcstein commented on README.md
> +Docker build . -t celestia-local-devnet
```suggestion
docker build . -t celestia-local-devnet
```

2023-07-31 13:15 UTC, jcstein commented on README.md
> +Docker run --platform linux/amd64 \
```suggestion
docker run --platform linux/amd64 \
```

2023-07-31 13:16 UTC, jcstein commented
> On a sidenote, what's the difference between port 26657 and 26658. In the docs it says
both are for RPC but I don't see 26657 used anywhere.
>

26657 is for celestia-app in this setup https://docs.celestia.org/nodes/celestia-app/#ports

2023-07-31 13:17 UTC, MSevey commented
@jcstein are the ports documented anywhere? which port is for which purpose? 
Even though it might be duplication, I think it is worthwhile also documenting in this repo why we are using the ports we do.

2023-07-31 13:23 UTC, jcstein requested changes
@HCastano would you like to add a piece about the different ports used here? you can find the details in celestia docs [here](https://docs.celestia.org/nodes/celestia-node-troubleshooting/#ports) and [here](https://docs.celestia.org/nodes/celestia-app/#ports)

2023-07-31 13:23 UTC, jcstein commented on README.md
> +Docker run --platform linux/amd64 \
we can safely remove the `--platform` flag here and in other instances

2023-07-31 16:38 UTC, HCastano commented on README.md
> +Docker build . -t celestia-local-devnet
Ouf, the dangers of automation 🙈

2023-07-31 16:41 UTC, HCastano commented
@jcstein The Celestia docs don't explain the difference between 26657 and 26658 though. Even in the troubleshooting docs the the text body mentions *57 while the table has info for *58 🤷‍♂️

Personally, my attempts to use port *57 for JSON-RPC requests fail, so I image there must be some difference.

2023-07-31 16:46 UTC, jcstein commented
to clarify, the troubleshooting page is for celestia-node

26658 is RPC for celestia-node https://docs.celestia.org/nodes/celestia-node-troubleshooting/#ports

26657 is RPC for celestia-app https://docs.celestia.org/nodes/celestia-app/#ports

2023-07-31 16:46 UTC, jcstein commented
it sounds like a Celestia-wide description of different ports would make sense both in this readme and in celestia docs

2023-08-01 15:00 UTC, HCastano commented
@jcstein gotcha, didn't realize they were for different node types. I've added a column with the node type for each port, let me know what you think

2023-08-01 16:08 UTC, jcstein commented
amazing! thank you again for the PR and contribution @HCastano 😄

2023-08-01 16:08 UTC, jcstein approved these changes
:shipit:

2023-08-02 17:47 UTC, nashqueue approved these changes

2023-08-02 17:47 UTC, merged

2023-08-02 17:48 UTC, nashqueue commented
Thank you for your contribution! :)